nodeLinker: node-modules

npmScopes:
  navikt:
    npmRegistryServer: https://npm.pkg.github.com
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN:-}

yarnPath: .yarn/releases/yarn-3.2.3.cjs
