apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: macgyver-frontend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://macgyver-frontend.dev.intern.nav.no"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "01a3d2a8-fabf-4bad-8017-2e9b5b8baba8"