apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: macgyver-frontend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://macgyver-frontend.dev.intern.nav.no"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      rules:
        - application: macgyver
          namespace: teamsykmelding
          cluster: dev-gcp
  env:
    - name: MACGYVER_BACKEND_SCOPE
      value: api://dev-gcp.teamsykmelding.macgyver/.default
